spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/side_user
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  cloud:
    aws:
      region:
        instance-profile: true
server:
  tomcat:
    access-log:
      enabled: true
      directory: logs
    basedir: .
kakao-auth:
  rest-api-key: c387fbf404982b87db2040c2898d96a9
  client-secret: vdLEOsu2ruHZUzUAOb0q2LUetlzH3gpy
  redirect-uri: http://localhost:3000/auth
token:
  access-token-secret: awey34634561235GWSDGVdsgvdsfhyfasdzehgysurhrt232t6347yetseryesrytasrgdasdrgvbasdfgbaedsfrghaewrgaewrghaerghaerha34qw67abcd
  refresh-token-expired: 1209600
  access-token-expired: 1209600
  issuer: team
cors:
  allow-origins: http://localhost:8080,http://localhost:3000
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /**
logging:
  level:
    # Set environment together: AWS_EC2_METADATA_DISABLED=true
    # ref: https://lannstark.tistory.com/71
    com.amazonaws.util.EC2MetadataUtils: error
