spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'
  datasource:
    username: ${mysql.name}
    password: ${mysql.password}
    url: ${mysql.url}
  jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
