spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
kakao-auth:
  rest-api-key:
  client-secret:
  redirect-uri:
token:
  access-token-secret:
  refresh-token-expired: 1209600
  access-token-expired: 1209600
  issuer: team
cors:
  allow-origins: http://localhost:8080,http://localhost:3000
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
logging:
  level:
    # Set environment together: AWS_EC2_METADATA_DISABLED=true
    # ref: https://lannstark.tistory.com/71
    com.amazonaws.util.EC2MetadataUtils: error
server:
  servlet:
    context-path: /api