spring:
  profiles:
    active: local
---

spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/config/bookRental/user_${spring.profiles.active}/
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  data:
    redis:
      port: 6379
      host: book-rental-cache-ro.v6ojg2.ng.0001.apn2.cache.amazonaws.com
kakao-auth:
  rest-api-key: ${kakao-auth.rest-api-key}
  client-secret: ${kakao-auth.client-secret}
  redirect-uri: ${kakao-auth.redirect-uri}
token:
  access-token-secret: ${token.access-token-secret}
  refresh-token-expired: 1209600
  access-token-expired: 1209600
  issuer: team
cors:
  allow-origins: ${cors.allow-origins}
