version: 0.0
os: linux

files:
  - source: /
    destination: /opt
permissions:
  - object: /opt
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 120
      runas: ec2-user
