name: CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description:
        required: true
env:
  SPRING_PROFILE: prod # 스프링 프로필
  MODULE_ROOT_PATH: ./main-api # 해당 모듈의 루트
  MODULE_JAR: ./main-api/build/libs/main-api.jar # 해당 모듈의 jar
  MODULE_DEPLOY_PATH: ./main-api/deploy # 해당 모듈의 deploy 디렉토리
  AWS_REGION: ap-northeast-2 # aws 리전
  ECR_IMAGE_TAG: ${{inputs.tags}}
jobs:
  build:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
      - name: step start
        run: "echo tags: $ECR_IMAGE_TAG"
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for root gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: create main boot jar
        run: ./gradlew bootJar -p $MODULE_ROOT_PATH

      - name: Copy Jar
        run: cp $MODULE_JAR deploy.jar

      - name: Copy appspec.yml
        run: cp $MODULE_DEPLOY_PATH/dev-appspec.yml appspec.yml

      - name: Copy deploy-sh.yml
        run: cp $MODULE_DEPLOY_PATH/dev-deploy.sh deploy.sh

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://book-rental-dev-deploy/user/$GITHUB_SHA.zip
      - name: Code Deploy
        run: aws deploy create-deployment --application-name book-rental-app-dev --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name book-rental-user-dev --s3-location bucket=book-rental-dev-deploy,bundleType=zip,key=user/$GITHUB_SHA.zip

#      - name: action-slack
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          author_name: Github Action Test
#          fields: repo,message,action,eventName,ref,workflow
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: always()